import java.io.*;
import java.util.ArrayList;
import java.util.List;



/**
 *
 * @author MICAEL MARCOS
 */
public class Main extends javax.swing.JFrame {
    List<ContaBancaria> conta = new ArrayList<>(); 
    ContaBancaria usuario;
    int numConta = 0;
        
    // Como o app não será conectado a um banco de dados será necessário salvar as informações dos usuários em um arquivo externo
    // para não perder os dados.
    
    public void salvarBackup() {
        String path = "C:\\Users\\MICAEL MARCOS\\Documents\\ADS 2° SEMESTRE\\PROGRAMAÇÃO ORIENTADA A OBJETOS\\UNIDADE 2\\MmBank_2\\src\\BackupContas.txt";
        
        try(BufferedWriter bw = new BufferedWriter(new FileWriter(path))) {
            for(ContaBancaria c : conta) {
                bw.write(c.getNome() + ","+c.getCPF()+"," + c.getSaldo()+"," + c.getSenha()+ ","+numConta);
                bw.newLine();
            }
        }
        catch(IOException e) {
            System.out.println(e);
        }
    
    }
    
    public void restauraBackup() {
        try(BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\MICAEL MARCOS\\Documents\\ADS 2° SEMESTRE\\PROGRAMAÇÃO ORIENTADA A OBJETOS\\UNIDADE 2\\MmBank_2\\src\\BackupContas.txt"))){
            String line = br.readLine();
            conta.clear();

            while(line != null) {
                String[] fields = line.split(",");
                String nome = fields[0];
                String CPF = fields[1];
                double saldo = Double.parseDouble(fields[2]);
                String senha = fields[3];
                int numConta = Integer.parseInt(fields[4]);
                
                conta.add(new ContaBancaria(nome, senha, CPF, saldo, numConta));
                line = br.readLine();
            }
        }
        catch(IOException e) {
            System.out.println(e);
        }
    }
/*
    List<Conta> listaConta = new ArrayList<>();
    
    String nome;
    long cpf;
    double saldo;
    int senha;
    

    public Main(String nome, long cpf, double saldo, int senha) {
        this.nome = nome;
        this.cpf = cpf;
        this.saldo = saldo;
        this.senha = senha;
    }
 public Main criaObjeto(int numConta) {
     Main mostrar = listaConta.get(numConta);
     return mostrar;
 }
*/
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form MmBankSwing
     */
    public Main() {
       
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CRIACONTA = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNomeCadastro = new javax.swing.JTextField();
        lblDepositoInicial = new javax.swing.JTextField();
        btnCriaContaDialog2 = new javax.swing.JButton();
        lblSenhaCadastro = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();
        lblCPFCadastro = new javax.swing.JFormattedTextField();
        areaLogada = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnSacar = new javax.swing.JToggleButton();
        btnDepositar = new javax.swing.JToggleButton();
        btnSair = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblSaldoVisor = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        telaSacar = new javax.swing.JDialog();
        lbl1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblValorSacar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnSacarConfirmar = new javax.swing.JButton();
        lblStatusSacar = new javax.swing.JLabel();
        lblSacarSenha = new javax.swing.JPasswordField();
        telaDepositar = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        btnConfirmaDeposito = new javax.swing.JButton();
        lblValorDeposito = new javax.swing.JTextField();
        lblStatusDepositar = new javax.swing.JLabel();
        telaTransferir = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblConfirmarTransferir = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        lblValorTransferir = new javax.swing.JTextField();
        lblStatusTransferir = new javax.swing.JLabel();
        lblCPFTransferir = new javax.swing.JFormattedTextField();
        lblSenhaTransferir = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        lblStatus1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Jlabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnCriarConta = new javax.swing.JButton();
        lblCPFConta = new javax.swing.JFormattedTextField();
        lblSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        CRIACONTA.setTitle("CRIAR CONTA");
        CRIACONTA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CRIACONTA.setFocusCycleRoot(false);
        CRIACONTA.setMinimumSize(new java.awt.Dimension(400, 350));
        CRIACONTA.setModal(true);
        CRIACONTA.setResizable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOVA CONTA");

        jLabel5.setText("Nome Completo");

        jLabel6.setText("CPF");

        jLabel7.setText("Depósito inicial (R$)");

        jLabel8.setText("Senha (6 Digitos)");

        lblDepositoInicial.setToolTipText("");

        btnCriaContaDialog2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnCriaContaDialog2.setText("CRIAR CONTA");
        btnCriaContaDialog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriaContaDialog2ActionPerformed(evt);
            }
        });

        try {
            lblCPFCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        lblCPFCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCPFCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CRIACONTALayout = new javax.swing.GroupLayout(CRIACONTA.getContentPane());
        CRIACONTA.getContentPane().setLayout(CRIACONTALayout);
        CRIACONTALayout.setHorizontalGroup(
            CRIACONTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CRIACONTALayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(CRIACONTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCriaContaDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CRIACONTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CRIACONTALayout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CRIACONTALayout.createSequentialGroup()
                            .addGroup(CRIACONTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(21, 21, 21)
                            .addGroup(CRIACONTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDepositoInicial)
                                .addComponent(lblNomeCadastro)
                                .addComponent(lblSenhaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(lblCPFCadastro)))))
                .addGap(30, 30, 30))
        );
        CRIACONTALayout.setVerticalGroup(
            CRIACONTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRIACONTALayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CRIACONTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRIACONTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCPFCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRIACONTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDepositoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRIACONTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCriaContaDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        areaLogada.setTitle("MINHA CONTA");
        areaLogada.setMinimumSize(new java.awt.Dimension(640, 380));
        areaLogada.setModal(true);
        areaLogada.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(85, 172, 238));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\MICAEL MARCOS\\Downloads\\logo area logada.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(41, 47, 51));

        jToggleButton1.setBackground(new java.awt.Color(85, 172, 238));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("TRANSFERIR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnSacar.setBackground(new java.awt.Color(85, 172, 238));
        btnSacar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSacar.setForeground(new java.awt.Color(255, 255, 255));
        btnSacar.setText("SACAR");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        btnDepositar.setBackground(new java.awt.Color(85, 172, 238));
        btnDepositar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDepositar.setForeground(new java.awt.Color(255, 255, 255));
        btnDepositar.setText("DEPOSITAR");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(85, 172, 238));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(225, 232, 237));

        lblNomeCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNomeCliente.setText("Olá!  Micael Marcos de Oliveira");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Seu saldo atual é de: ");

        jPanel7.setBackground(new java.awt.Color(102, 117, 127));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBackground(new java.awt.Color(102, 117, 127));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("R$");

        lblSaldoVisor.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblSaldoVisor.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoVisor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldoVisor.setText("0,00");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSaldoVisor)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldoVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Copyright 2025 @MMCode");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addGap(35, 35, 35)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        javax.swing.GroupLayout areaLogadaLayout = new javax.swing.GroupLayout(areaLogada.getContentPane());
        areaLogada.getContentPane().setLayout(areaLogadaLayout);
        areaLogadaLayout.setHorizontalGroup(
            areaLogadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(areaLogadaLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        areaLogadaLayout.setVerticalGroup(
            areaLogadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaLogadaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(areaLogadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        telaSacar.setTitle("SACAR");
        telaSacar.setMinimumSize(new java.awt.Dimension(300, 250));
        telaSacar.setModal(true);
        telaSacar.setResizable(false);

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl1.setText("SACAR");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("VALOR");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("SENHA");

        btnSacarConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSacarConfirmar.setText("CONFIRMAR");
        btnSacarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarConfirmarActionPerformed(evt);
            }
        });

        lblSacarSenha.setText("jPasswordField1");

        javax.swing.GroupLayout telaSacarLayout = new javax.swing.GroupLayout(telaSacar.getContentPane());
        telaSacar.getContentPane().setLayout(telaSacarLayout);
        telaSacarLayout.setHorizontalGroup(
            telaSacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaSacarLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(telaSacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(telaSacarLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSacarSenha))
                    .addGroup(telaSacarLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaSacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(telaSacarLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lbl1))))
                    .addComponent(btnSacarConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatusSacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        telaSacarLayout.setVerticalGroup(
            telaSacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaSacarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(telaSacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorSacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaSacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSacarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacarConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatusSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        telaDepositar.setTitle("DEPOSITAR");
        telaDepositar.setMinimumSize(new java.awt.Dimension(300, 250));
        telaDepositar.setModal(true);
        telaDepositar.setResizable(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("DEPOSITAR");

        btnConfirmaDeposito.setText("CONFIRMAR");
        btnConfirmaDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaDepositoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaDepositarLayout = new javax.swing.GroupLayout(telaDepositar.getContentPane());
        telaDepositar.getContentPane().setLayout(telaDepositarLayout);
        telaDepositarLayout.setHorizontalGroup(
            telaDepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDepositarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(telaDepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(telaDepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblStatusDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConfirmaDeposito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(telaDepositarLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel16)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        telaDepositarLayout.setVerticalGroup(
            telaDepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDepositarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnConfirmaDeposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatusDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        telaTransferir.setTitle("TRANSFERIR");
        telaTransferir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        telaTransferir.setMinimumSize(new java.awt.Dimension(400, 350));
        telaTransferir.setModal(true);
        telaTransferir.setResizable(false);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("TRANSFERIR");

        jLabel19.setText("CPF");

        jLabel20.setText("Valor");

        lblConfirmarTransferir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblConfirmarTransferir.setText("CONFIRMAR");
        lblConfirmarTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblConfirmarTransferirActionPerformed(evt);
            }
        });

        jLabel21.setText("Digite sua senha");

        try {
            lblCPFTransferir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblSenhaTransferir.setText("jPasswordField1");

        javax.swing.GroupLayout telaTransferirLayout = new javax.swing.GroupLayout(telaTransferir.getContentPane());
        telaTransferir.getContentPane().setLayout(telaTransferirLayout);
        telaTransferirLayout.setHorizontalGroup(
            telaTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaTransferirLayout.createSequentialGroup()
                .addGroup(telaTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaTransferirLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(telaTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(telaTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblValorTransferir)
                            .addComponent(lblConfirmarTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatusTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCPFTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(lblSenhaTransferir)))
                    .addGroup(telaTransferirLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel17)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        telaTransferirLayout.setVerticalGroup(
            telaTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaTransferirLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(telaTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblCPFTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(lblValorTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblSenhaTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblConfirmarTransferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatusTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENTRAR");
        setMinimumSize(new java.awt.Dimension(400, 350));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(85, 172, 238));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Copyright 2025 @MMCode");

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        Jlabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jlabel1.setText("CPF");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("SENHA");

        btnEntrar.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnCriarConta.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnCriarConta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCriarConta.setText("CRIAR CONTA");
        btnCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarContaActionPerformed(evt);
            }
        });

        try {
            lblCPFConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblSenha.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCriarConta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lblCPFConta, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel1)
                    .addComponent(lblCPFConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCriarConta)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(lblStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MICAEL MARCOS\\Downloads\\logo area logada.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel3)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        restauraBackup();
        String senha = new String(lblSenha.getPassword());
        String CPF = lblCPFConta.getText();
        
        for(ContaBancaria us : conta){
            if(us.autenticaUsuario(CPF, senha)) {
                areaLogada.setLocationRelativeTo(null);
                lblNomeCliente.setText("Olá! " + us.getNome());
                lblSaldoVisor.setText(String.format("%.2f", us.getSaldo()));
                this.usuario = us;
                areaLogada.setVisible(true);
                break;
            }
            
        }
        lblStatus1.setText("Login ou senha incorretos!");
/*  
        int osenha = Integer.parseInt(lblSenha.getText());
        int numConta = Integer.parseInt(lblNumConta.getText()); 
        numContaAtual = numConta;
        if(numConta>listaConta.size()-1 || numConta<0) {
            lblStatus1.setText("Login ou senha incorretos!");
        } else {
            Main mostrar = criaObjeto(numContaAtual);
            // Main mostrar = listaConta.get(numConta);
            System.out.println("Entrou no laço " + mostrar.senha);

            if(osenha == mostrar.senha) {
                areaLogada.setLocationRelativeTo(null);
                lblNomeCliente.setText("Olá! " + mostrar.nome);
                lblSaldoVisor.setText(String.format("%.2f", mostrar.saldo));
                areaLogada.setVisible(true);
                
                
            } else{
                lblStatus1.setText("Login ou senha incorretos!");
            }      
        }
*/
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarContaActionPerformed
        CRIACONTA.setLocationRelativeTo(null);
        CRIACONTA.setVisible(true);
        lblStatus.setText("");

        /*
        lblMostraNumConta.setText(String.valueOf(numContaTotal));
        CRIACONTA.setLocationRelativeTo(null);
        CRIACONTA.setVisible(true);
*/
    }//GEN-LAST:event_btnCriarContaActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        telaSacar.setVisible(true);
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btnSacarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarConfirmarActionPerformed
        if(usuario.autenticaSenha(new String(lblSacarSenha.getPassword()))) {
            conta.get(usuario.getNumConta()).removerSaldo(Double.parseDouble(lblValorSacar.getText()));
            lblStatusSacar.setText("Saque efetuado com sucesso!");
            lblSaldoVisor.setText(String.format("%.2f", usuario.getSaldo()));
            salvarBackup();


        } else {
            lblStatusSacar.setText("Verique o valor e a senha inserida!");
        }
    }//GEN-LAST:event_btnSacarConfirmarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        telaDepositar.setVisible(true);
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnConfirmaDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaDepositoActionPerformed
        conta.get(usuario.getNumConta()).adicionaSaldo(Double.parseDouble(lblValorDeposito.getText()));
        usuario.adicionaSaldo(Double.parseDouble(lblValorDeposito.getText()));
        lblSaldoVisor.setText(String.format("%.2f", usuario.getSaldo()));
        salvarBackup();
        telaDepositar.setVisible(false);
    }//GEN-LAST:event_btnConfirmaDepositoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        telaTransferir.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void lblConfirmarTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblConfirmarTransferirActionPerformed
        
/*
        int asenha = Integer.parseInt(lblSenhaTransferir.getText());
        long acpf = Long.parseLong(lblCPFTransferir.getText());
        int conta = Integer.parseInt(lblContaTransferir.getText());
        double valor = Double.parseDouble(lblValorTransferir.getText());
        Main mostrar = criaObjeto(numContaAtual);
        if(conta < numContaTotal) {
            Main Transferir = criaObjeto(conta);
            if(Transferir.cpf == acpf && asenha == mostrar.senha && valor<mostrar.saldo && valor>0) {
                Transferir.saldo += valor;
                mostrar.saldo -= valor;
                lblStatusTransferir.setText("Concluido com sucesso!");
            } else {
                lblStatusTransferir.setText("Verifique os dados!");

            }
        } else {
                lblStatusTransferir.setText("Verifique os dados!");

            }
        lblSaldoVisor.setText(String.format("%.2f", mostrar.saldo));
*/
    }//GEN-LAST:event_lblConfirmarTransferirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        areaLogada.dispose();
        usuario = null;
    }//GEN-LAST:event_btnSairActionPerformed

    private void lblCPFCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCPFCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCPFCadastroActionPerformed

    private void btnCriaContaDialog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriaContaDialog2ActionPerformed
        try {
            String nome = lblNomeCadastro.getText();
            String cpf = lblCPFCadastro.getText();
            double saldo = Integer.parseInt(lblDepositoInicial.getText());
            String senha = new String(lblSenhaCadastro.getPassword());
            numConta++;
            ContaBancaria c = new ContaBancaria(nome, senha, cpf, saldo, numConta);
            conta.add(c);
            salvarBackup();
            lblStatus.setText("Cadastro efetuado com sucesso!");
            lblNomeCadastro.setText("");
            lblCPFCadastro.setText("");
            lblDepositoInicial.setText("");
            lblSenhaCadastro.setText("");
            
            
        } catch(Exception e) {
            lblStatus.setText("Ocorreu um erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCriaContaDialog2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {  
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CRIACONTA;
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JDialog areaLogada;
    private javax.swing.JButton btnConfirmaDeposito;
    public javax.swing.JButton btnCriaContaDialog2;
    private javax.swing.JButton btnCriarConta;
    private javax.swing.JToggleButton btnDepositar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JToggleButton btnSacar;
    private javax.swing.JButton btnSacarConfirmar;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JFormattedTextField lblCPFCadastro;
    private javax.swing.JFormattedTextField lblCPFConta;
    private javax.swing.JFormattedTextField lblCPFTransferir;
    private javax.swing.JButton lblConfirmarTransferir;
    private javax.swing.JTextField lblDepositoInicial;
    private javax.swing.JTextField lblNomeCadastro;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JPasswordField lblSacarSenha;
    private javax.swing.JLabel lblSaldoVisor;
    private javax.swing.JPasswordField lblSenha;
    private javax.swing.JPasswordField lblSenhaCadastro;
    private javax.swing.JPasswordField lblSenhaTransferir;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblStatusDepositar;
    private javax.swing.JLabel lblStatusSacar;
    private javax.swing.JLabel lblStatusTransferir;
    private javax.swing.JTextField lblValorDeposito;
    private javax.swing.JTextField lblValorSacar;
    private javax.swing.JTextField lblValorTransferir;
    private javax.swing.JDialog telaDepositar;
    private javax.swing.JDialog telaSacar;
    private javax.swing.JDialog telaTransferir;
    // End of variables declaration//GEN-END:variables

}
